apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-wl7o
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-wl7o
    app.kubernetes.io/part-of: load-app-e656939e-ad99-40fd-92f5-c38ff0033d70
  name: devfile-sample-wl7ovktj
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: devfile-sample-wl7o
    weight: null
status: {}
