apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-wl7o
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-wl7o
    app.kubernetes.io/part-of: load-app-e656939e-ad99-40fd-92f5-c38ff0033d70
  name: devfile-sample-wl7o
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-wl7o
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-wl7o
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-78-tenant/load-app-e656939e-ad99-40fd-92f5-c38ff0033d70/devfile-sample-wl7o@sha256:6e8bfbcbf8f5c5bb1d9e8c049cd838f7fabea47e9dde07e06e87457c0c64dfd3
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
