apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-wl7o
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-wl7o
    app.kubernetes.io/part-of: load-app-e656939e-ad99-40fd-92f5-c38ff0033d70
  name: devfile-sample-wl7o
spec:
  ports:
  - name: "3001"
    port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: devfile-sample-wl7o
status:
  loadBalancer: {}
